version: '2'
services:
  preps-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13
    volumes:
      - ~/volumes/jhipster/preps/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 11003:9200
      - 9300:9300
    #    command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
