version: '2'
services:
  preps-postgresql:
    image: postgres:12.2
    volumes:
      - ~/volumes/jhipster/preps/postgresql/:/var/lib/prepsApp/data/
    environment:
      - POSTGRES_USER=${PG_DATABASE_DEV_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - POSTGRES_DB=preps
    ports:
      - 11002:5432
