version: '2'
services:
  preps-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/preps/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=preps
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
